apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "3"
    deployment.kubernetes.io/max-replicas: "4"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-05-19T18:57:41Z"
  generation: 1
  labels:
    app: go-app
    pod-template-hash: 8584bfc496
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/desired-replicas: {}
          f:deployment.kubernetes.io/max-replicas: {}
          f:deployment.kubernetes.io/revision: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"ff870a08-e41c-4390-9285-dfb62714d043"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:replicas: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
            f:pod-template-hash: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:pod-template-hash: {}
          f:spec:
            f:containers:
              k:{"name":"go-application-sha256-1"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
      f:status:
        f:availableReplicas: {}
        f:fullyLabeledReplicas: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-19T19:31:41Z"
  name: go-application-deployment-8584bfc496
  namespace: go-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: go-application-deployment
    uid: ff870a08-e41c-4390-9285-dfb62714d043
  resourceVersion: "1429209"
  selfLink: /apis/apps/v1/namespaces/go-app/replicasets/go-application-deployment-8584bfc496
  uid: bad89069-0d3b-4bbb-91cb-1a8a3056552c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
      pod-template-hash: 8584bfc496
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        pod-template-hash: 8584bfc496
    spec:
      containers:
      - image: gcr.io/simple-go-project-313922/go-application@sha256:2d94e180bdc009a28d008ff7e87fe053f1e286c4a6159c9a7c6e07017746a607
        imagePullPolicy: IfNotPresent
        name: go-application-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
