apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "go-app"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "go-application-deployment"
  namespace: "go-app"
  labels:
    app: "go-application-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-application-deployment"
  template:
    metadata:
      labels:
        app: "go-application-deployment"
    spec:
      containers:
      - name: "go-application-sha256-1"
        image: "gcr.io/simple-go-project-313922/go-application@sha256:2d94e180bdc009a28d008ff7e87fe053f1e286c4a6159c9a7c6e07017746a607"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "go-application-deployment-hpa-utum"
  namespace: "go-app"
  labels:
    app: "go-application-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "go-application-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
