apiVersion: v1
kind: Service
metadata:
  name: go-app-service1
spec:
  selector:
    app: metrics
    department: sales
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080