---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "go-app"
  namespace: "go-app"
  labels:
    app: "go-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-app"
  template:
    metadata:
      labels:
        app: "go-app"
    spec:
      containers:
      - name: "go-app-sha256-1"
        image: "gcr.io/PROJECT_ID/IMAGE:GITHUB_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "go-app-hpa-u4zh"
  namespace: "go-app"
  labels:
    app: "go-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "go-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80