---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "go-app"
  namespace: go-app-namespace
  labels:
    app: "go-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-app"
  template:
    metadata:
      labels:
        app: "go-app"
    spec:
      serviceAccountName: postgres-sa
      containers:
      - name: "go-app-sha256-1"
        image: "gcr.io/simple-go-app-315700/go-app:22"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=simple-go-app-315700:us-central1:go-app-postgres=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "0.1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "go-app-hpa-u4zh"
  labels:
    app: "go-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "go-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
    


