name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
      
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USER }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.3.0
  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/firstApp/
        file: ./src/firstApp/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/firstapp:latest
