name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        go get -u gorm.io/gorm
        go get -u gorm.io/driver/postgres
        go get github.com/Sirupsen/logrus github.com/mitchellh/cli github.com/mitchellh/go-homedir gopkg.in/yaml.v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
